OctopusDeploy/OpenIDConnectAuthenticationProviders

source/Octopus.Server.Extensibility.Authentication.AzureAD/Octopus.Server.Extensibility.Authentication.AzureAD.csproj
source/Octopus.Server.Extensibility.Authentication.GoogleApps/Octopus.Server.Extensibility.Authentication.GoogleApps.csproj
source/Octopus.Server.Extensibility.Authentication.OpenIDConnect/Infrastructure/Nonce.cs
source/Octopus.Server.Extensibility.Authentication.OpenIDConnect/Octopus.Server.Extensibility.Authentication.OpenIdConnect.csproj
source/Octopus.Server.Extensibility.Authentication.OpenIDConnect/Tokens/OpenIDConnectAuthTokenHandler.cs

In response to https://trello.com/c/ryIuqdfo

Security Review

---

source/Octopus.Server.Extensibility.Authentication.AzureAD/Octopus.Server.Extensibility.Authentication.AzureAD.csproj
source/Octopus.Server.Extensibility.Authentication.AzureAD/Web/AzureADUserAuthenticationAction.cs
source/Octopus.Server.Extensibility.Authentication.AzureAD/packages.config
source/Octopus.Server.Extensibility.Authentication.GoogleApps/Octopus.Server.Extensibility.Authentication.GoogleApps.csproj
source/Octopus.Server.Extensibility.Authentication.GoogleApps/Web/GoogleAppsUserAuthenticationAction.cs
source/Octopus.Server.Extensibility.Authentication.GoogleApps/packages.config
source/Octopus.Server.Extensibility.Authentication.OpenIDConnect/Octopus.Server.Extensibility.Authentication.OpenIdConnect.csproj
source/Octopus.Server.Extensibility.Authentication.OpenIDConnect/OpenIDConnectAuthenticationProvider.cs
source/Octopus.Server.Extensibility.Authentication.OpenIDConnect/Web/UserAuthenticationAction.cs
source/Octopus.Server.Extensibility.Authentication.OpenIDConnect/packages.config

Added checks for open redirection attacks and updated packages to get latest virtual directory path handling implementation.

Check for open redirection attacks

---

source/Octopus.Server.Extensibility.Authentication.AzureAD/Web/AzureADUserAuthenticatedAction.cs
source/Octopus.Server.Extensibility.Authentication.GoogleApps/Web/GoogleAppsUserAuthenticatedAction.cs
source/Octopus.Server.Extensibility.Authentication.OpenIDConnect/Infrastructure/IPrincipalToUserResourceMapper.cs
source/Octopus.Server.Extensibility.Authentication.OpenIDConnect/Infrastructure/PrincipalToUserResourceMapper.cs
source/Octopus.Server.Extensibility.Authentication.OpenIDConnect/Octopus.Server.Extensibility.Authentication.OpenIdConnect.csproj
source/Octopus.Server.Extensibility.Authentication.OpenIDConnect/OpenIdConnectExtension.cs
source/Octopus.Server.Extensibility.Authentication.OpenIDConnect/Web/UserAuthenticatedAction.cs

After testing fairly thoroughly I believe we need to avoid using the Query String as a communication protocol to the sign in page. Each of these errors which can occur really indicate a Bad Request in some form or another.
At least this way the error is noisy and accessible, and should be less susceptible to side-effecting the application.
I've also removed a handful of duplicate error handling logic.
Relates to https://github.com/OctopusDeploy/Issues/issues/2988

Iterate on how we handle post-external-authentication errors

---

source/Octopus.Server.Extensibility.Authentication.AzureAD/AzureADAuthenticationProvider.cs
source/Octopus.Server.Extensibility.Authentication.GoogleApps/GoogleAppsAuthenticationProvider.cs
source/Octopus.Server.Extensibility.Authentication.OpenIDConnect/Configuration/OpenIDConnectConfigurationStore.cs
source/Octopus.Server.Extensibility.Authentication.OpenIDConnect/OpenIDConnectAuthenticationProvider.cs

Updating validation around the issuer for OpenID login providers so this is clear when you run the `configure` command against your Octopus Server that this should be an absolute uri.
If they've already run a bad configure 'issuer' command against their instance, the `ReasonsWhyConfigIsIncomplete` validation will detect an invalid issuer URI and generate a log in their server logs.
If they're running the configure command from this point on, and try to call `SetIssuer` for their given login provider, it will now detect if they're trying to enter a GUID and inform them accordingly (and then fallback to also check if it's a valid URI).
Once this PR is approved, I'll make another PR for Octopus.Server (to include this updated version) and merge.
Fixes OctopusDeploy/Issues#3379

Updating validation around the issuer for OpenID login providers

---

source/Octopus.Server.Extensibility.Authentication.AzureAD/Issuer/AzureADKeyRetriever.cs
source/Octopus.Server.Extensibility.Authentication.GoogleApps/Issuer/GoogleKeyRetriever.cs
source/Octopus.Server.Extensibility.Authentication.OpenIDConnect/Certificates/IKeyRetriever.cs
source/Octopus.Server.Extensibility.Authentication.OpenIDConnect/Certificates/KeyRetriever.cs
source/Octopus.Server.Extensibility.Authentication.OpenIDConnect/Tokens/OpenIDConnectAuthTokenHandler.cs
source/Octopus.Server.Extensibility.Authentication.Tests/Helpers/RS256AlgorithmRsaOnly.cs
source/Octopus.Server.Extensibility.Authentication.Tests/Octopus.Server.Extensibility.Authentication.Tests.csproj
source/Octopus.Server.Extensibility.Authentication.Tests/OpenIdConnect/Tokens/CustomOpenIDConnectAuthTokenHandler.cs
source/Octopus.Server.Extensibility.Authentication.Tests/OpenIdConnect/Tokens/OpenIDConnectAuthTokenHandlerFixture.cs
source/Octopus.Server.Extensibility.Authentication.Tests/Properties/AssemblyInfo.cs
source/Octopus.Server.Extensibility.Authentication.Tests/app.config
source/Octopus.Server.Extensibility.Authentication.Tests/packages.config
source/OpenIDConnectAuthenticationProvider.sln

Relates to https://github.com/OctopusDeploy/Issues/issues/3621
Summary of changes:
+ Simplified caching logic in the KeyRetriever and provided flag to force cache reload.
+ GetPrincipalFromToken will now, upon detection of invalid signature, flush the cache, reload the keys before validating token.
+ The audience & issuer token parameters are now validated
+ Added unit tests to verify the GetPrincipalAsync/GetPrincipalFromToken methods of the OpenIDConnectAuthTokenHandler

Improvements to key cache handling

---

source/Node.Extensibility.Authentication.OpenIDConnect/Configuration/IOpenIDConnectConfigurationWithRoleStore.cs
source/Node.Extensibility.Authentication.OpenIDConnect/Configuration/OpenIDConnectConfigurationWithRole.cs
source/Node.Extensibility.Authentication.OpenIDConnect/Issuer/AuthorizationEndpointUrlBuilder.cs
source/Node.Extensibility.Authentication.OpenIDConnect/Tokens/AuthTokenHandler.cs
source/Node.Extensibility.Authentication.OpenIDConnect/Tokens/ClaimsPrincipleContainer.cs
source/Node.Extensibility.Authentication.Tests/Node.Extensibility.Authentication.Tests.csproj
source/Node.Extensibility.Authentication.Tests/OpenIdConnect/Tokens/CustomOpenIDConnectAuthTokenHandler.cs
source/Node.Extensibility.Authentication.Tests/OpenIdConnect/Tokens/CustomOpenIDConnectWithRoleAuthTokenHandler.cs
source/Node.Extensibility.Authentication.Tests/OpenIdConnect/Tokens/OpenIDConnectAuthTokenHandlerFixture.cs
source/Node.Extensibility.Authentication.Tests/OpenIdConnect/Tokens/OpenIDConnectWithRolesAuthTokenHandlerFixture.cs
source/Node.Extensibility.Authentication.Tests/OpenIdConnect/Tokens/OpenIDFixtureBase.cs
source/OpenIDConnectAuthenticationProvider.sln.DotSettings
source/Server.Extensibility.Authentication.AzureAD/Configuration/AzureADConfiguration.cs
source/Server.Extensibility.Authentication.AzureAD/Configuration/AzureADConfigurationStore.cs
source/Server.Extensibility.Authentication.AzureAD/Configuration/IAzureADConfigurationStore.cs
source/Server.Extensibility.Authentication.AzureAD/Tokens/AzureADAuthTokenHandler.cs
source/Server.Extensibility.Authentication.Okta/Configuration/IOktaConfigurationStore.cs
source/Server.Extensibility.Authentication.Okta/Configuration/OktaConfiguration.cs
source/Server.Extensibility.Authentication.Okta/Configuration/OktaConfigurationStore.cs
source/Server.Extensibility.Authentication.Okta/OktaExtension.cs
source/Server.Extensibility.Authentication.Okta/Tokens/OktaAuthTokenHandler.cs
source/Server.Extensibility.Authentication.OpenIDConnect/Configuration/OpenIDConnectConfigurationWithRoleStore.cs
source/Server.Extensibility.Authentication.OpenIDConnect/Tokens/OpenIDConnectAuthTokenWithRolesHandler.cs
source/Server.Extensibility.Authentication.OpenIDConnect/Web/UserAuthenticatedAction.cs
tools/packages.config

We'd been holding the RoleClaimType a bit wrong. The crux of this fix is the following
```
var groups = principal.FindAll(ClaimTypes.Role)
.Concat(principal.FindAll(roleClaimType))
.Select(c => c.Value).ToArray();
```
in `OpenIDConnectAuthTokenWithRolesHandler`. The rest of this PR is refactoring so AzureAD and Okta are sharing this now instead of having their own copies of it. The refactor is also so that the groups are passed back out of `GetPrincipalAsync` in the `PrincipalContainer`.
Have retested against AzureAD and Okta.

Fix group claims handling

---

source/Node.Extensibility.Authentication.OpenIDConnect/Node.Extensibility.Authentication.OpenIDConnect.csproj
source/Node.Extensibility.Authentication.Tests/Node.Extensibility.Authentication.Tests.csproj
source/Node.Extensibility.Authentication.Tests/packages.config
source/Server.Extensibility.Authentication.AzureAD/Configuration/AzureADConfigurationSettings.cs
source/Server.Extensibility.Authentication.AzureAD/Configuration/AzureADConfigurationStore.cs
source/Server.Extensibility.Authentication.GoogleApps/Configuration/GoogleAppsConfigurationSettings.cs
source/Server.Extensibility.Authentication.GoogleApps/Configuration/GoogleAppsConfigurationStore.cs
source/Server.Extensibility.Authentication.Okta/Configuration/OktaConfigurationSettings.cs
source/Server.Extensibility.Authentication.Okta/Configuration/OktaConfigurationStore.cs
source/Server.Extensibility.Authentication.OpenIDConnect/Configuration/OpenIDConnectConfigurationStore.cs
source/Server.Extensibility.Authentication.OpenIDConnect/Configuration/OpenIDConnectConfigurationWithRoleStore.cs
source/Server.Extensibility.Authentication.OpenIDConnect/Configuration/OpenIdConnectConfigurationSettings.cs
source/Server.Extensibility.Authentication.OpenIDConnect/Server.Extensibility.Authentication.OpenIdConnect.csproj

The resource mapping part of `Octopus.Server.Extensibility` has changed. I'm updating this solution accordingly.

Update resource mapping server extensibility

---

source/Server.Extensibility.Authentication.OpenIDConnect/Server.Extensibility.Authentication.OpenIdConnect.csproj
source/Server.Extensibility.Authentication.OpenIDConnect/Web/UserAuthenticatedAction.cs

which means searching by identity could return multiple users, but for this provider we should only ever get 0 or 1 back

email is no longer unique

---

source/Server.Extensibility.Authentication.OctopusID/Configuration/OctopusIDConfiguration.cs
source/Server.Extensibility.Authentication.OctopusID/Configuration/OctopusIDDatabaseInitializer.cs

Fixes an issue where Octopus ID is always enabled, and started emitting Warning messages about incomplete config into the server logs.

Change the default enabled state for OctopusID

---

source/Node.Extensibility.Authentication.OpenIDConnect/Identities/IdentityCreator.cs

When a user logs in via an external auth provider (Google, Octopus ID, etc), we look at existing Octopus users and decide if any match and should be linked.
This PR ensures that we _do not_ match and link based on the _display name_ of existing users.
This PR brings the behavior for new identities into line with [the way we display external logins in the UI](https://github.com/OctopusDeploy/OpenIDConnectAuthenticationProviders/blob/master/source/Node.Extensibility.Authentication.OpenIDConnect/OpenIDConnectAuthenticationProvider.cs#L100), so it's likely this was always the intention and this is just a straight up bug

fix(identity): Display names are not an identifying claim for external identities

---

source/Server.Extensibility.Authentication.OctopusID/Configuration/OctopusIDConfigureCommands.cs
source/Server.Extensibility.Authentication.OpenIDConnect/Configuration/OpenIDConnectConfigureCommands.cs

If the Octopus ID options aren't hidden then they appear for `octopus.server.exe configure --help`, which also means they appear automatically in the docs, which we'd rather not have.
These command are still available, they are just hidden from the users.
Following is the updated output of the configure command help
Following is output from changing the Octopus ID enabled state (the warning is expected, based on the config I have setup)

Hide the Octopus ID command line configuration options

---

source/Node.Extensibility.Authentication.OpenIDConnect/OpenIDConnectExtension.cs
source/Node.Extensibility.Authentication.OpenIDConnect/Tokens/AuthTokenHandler.cs
source/Node.Extensibility.Authentication.Tests/Node.Extensibility.Authentication.Tests.csproj
source/Node.Extensibility.Authentication.Tests/OctopusID/OctopusIdConfigDiscovererFixture.cs
source/Node.Extensibility.Authentication.Tests/OpenIdConnect/Tokens/CustomOpenIDConnectAuthTokenHandler.cs
source/Node.Extensibility.Authentication.Tests/OpenIdConnect/Tokens/CustomOpenIDConnectWithRoleAuthTokenHandler.cs
source/Server.Extensibility.Authentication.AzureAD/AzureADExtension.cs
source/Server.Extensibility.Authentication.AzureAD/Tokens/AzureADAuthTokenHandler.cs
source/Server.Extensibility.Authentication.GoogleApps/GoogleAppsExtension.cs
source/Server.Extensibility.Authentication.GoogleApps/Tokens/GoogleAuthTokenHandler.cs
source/Server.Extensibility.Authentication.OctopusID/IOctopusIdentityProviderConfigDiscoverer.cs
source/Server.Extensibility.Authentication.OctopusID/OctopusIDExtension.cs
source/Server.Extensibility.Authentication.OctopusID/OctopusIdConfigDiscoverer.cs
source/Server.Extensibility.Authentication.OctopusID/StringExtensions.cs
source/Server.Extensibility.Authentication.OctopusID/Tokens/OctopusIDAuthTokenHandler.cs
source/Server.Extensibility.Authentication.OctopusID/Web/OctopusIDUserAuthenticationAction.cs
source/Server.Extensibility.Authentication.Okta/OktaExtension.cs
source/Server.Extensibility.Authentication.Okta/Tokens/OktaAuthTokenHandler.cs
source/Server.Extensibility.Authentication.OpenIDConnect/Tokens/OpenIDConnectAuthTokenHandler.cs
source/Server.Extensibility.Authentication.OpenIDConnect/Tokens/OpenIDConnectAuthTokenWithRolesHandler.cs

As discussed [via Slack](https://octopusdeploy.slack.com/archives/CLF5AF83V/p1568247917034200):
1. We want to write a mega-end-to-end test that covers the interaction between a provisioned Cloud v2 instance and Octopus ID SSO
2. We want that test to run against an in-memory instance of `Octofront.Web.Hosted` (for provisioning) and `Octofront.Web.Public` (for Octopus ID SSO)
We cannot write such a test, because the provisioned Cloud v2 instance attempts to place a request to the identity provider at `localhost/.well-known/openid-configuration` but of course, in that context, `localhost`  is the Cloud instance's host in Azure, not the test runner, so the request fails.
Find a way to allow Server to place the request directly to `localhost`, by integrating something like `ngrok` into the …

feat(OctopusID): Support localhost issuers for Octopus ID

---

source/Server.Extensibility.Authentication.OctopusID/Web/Static/areas/users/octopusId_auth_provider.js
source/Server.Extensibility.Authentication.OctopusID/Web/Static/styles/octopusId.css

I've updated the background colour and text colour on the **Sign in with your Octopus ID** button.  I've also swapped out the PNG we were using for the font version of our logo to easily switch colours on hover.
**Here's the aim:**
Related to Trello card: https://trello.com/c/1YaP8ofQ/79-hover-state-on-button-is-too-dark
Please check and review that I haven't broken anything, and it looks like the design above.  Thanks

Update Hover colours on OctopusID Sign In screen

---

source/Server.OctopusID/Web/Static/styles/octopusId.css

The Octopus ID button had no background color and it blended into the background.

Bug octopus id button

---

source/Client.OpenIDConnect/Client.OpenIDConnect.csproj

This pull request depends on https://github.com/OctopusDeploy/OctopusClients/pull/587.
For historical reasons, we need a version of `Octopus.Client.nupkg` which contains a single DLL which is ILMerged so that it can be loaded by a single line in a PowerShell script.
For modern reasons, we need a version (now called `Octopus.Server.Client.nupkg`) which contains a DLL which is _not_ ILMerged and has the usual references to other libraries like `Octopus.TinyTypes`, `Newtonsoft.Json` etc.
This PR updates this library to have a dependency only on the non-ILMerged `Octopus.Server.Client` package.
Our serialisation approach can now cope with tiny types in message contracts.

Use non-ILMerged Octopus client

---

source/Server.AzureAD/Server.AzureAD.csproj
source/Server.OctopusID/Server.OctopusID.csproj
source/Server.Okta/Configuration/OktaConfiguration.cs
source/Server.Okta/Identities/OktaIdentityCreator.cs
source/Server.Okta/Server.Okta.csproj
source/Server.OpenIDConnect.Common/Identities/IIdentityCreator.cs
source/Server.OpenIDConnect.Common/Identities/IdentityCreator.cs
source/Server.OpenIDConnect.Common/Web/UserAuthenticatedAction.cs

When trying to match an Okta user with the same username and email address in both Octopus and Okta, it was failing to find the user when the preferred username was the Okta username (throwing a user exists error when trying to create the user), but would create a new user if the preferred username was the Okta Email field.
This change adds the Okta Preferred Username value as an identifier, if not already in the list of identifiers.  This should allow the user to be found by username (Okta's preferred username), and then verified by Email address.
Before:
When Okta is set up to use referred_username as the Username Claim Type:
After:

Adding the username as an identifier in Okta

---

source/Server.Okta/Identities/OktaIdentityCreator.cs
source/Server.OpenIDConnect.Common/Identities/IIdentityCreator.cs
source/Server.OpenIDConnect.Common/Identities/IdentityCreator.cs
source/Server.OpenIDConnect.Common/Web/UserAuthenticatedAction.cs

This back-ports a fix, to allow Okta to use the preferred_username as a the username identifier when matching Okta users in Octopus.  (https://github.com/OctopusDeploy/OpenIDConnectAuthenticationProviders/pull/48)

Andrew w/okta preferred username

---

source/Server.GoogleApps/Web/Static/areas/users/googleApps_auth_provider.js
source/Server.GoogleApps/Web/Static/images/google_signin_buttons/icon-google.svg
source/Server.GoogleApps/Web/Static/styles/googleApps.css

This PR updates the google auth button to closer align with google's [guidelines](https://developers.google.com/identity/branding-guidelines). We were previously using the G+ logo which has been dead for quite some time.
Related Server [PR](https://github.com/OctopusDeploy/OctopusDeploy/pull/10371)

Update google auth button to closer align with google guidelines

---

source/Server.OctopusID/Configuration/OctopusIDConfigurationResource.cs

Our Cloud Platform currently uses the CLI to configure Octopus ID on a hosted instance. It would be quicker and more reliable to do this via the REST API.
We need to make these properties writable to facilitate this. Octopus Server will then enforce the appropriate permissions
https://trello.com/c/EHAyPCu1/690-improve-the-performance-of-configureinstanceaccess-step-in-customizehostedinstancebackgroundprocess
https://octopusdeploy.slack.com/archives/C01HZFJRYSH/p1643684744224069?thread_ts=1643590290.269429&cid=C01HZFJRYSH

Make OctoupsID configuration writable so our Cloud Platform can use it configure hosted Octopus Server instances

---

source/Server.OpenIDConnect.Common/Issuer/AuthorizationEndpointUrlBuilder.cs
source/Server.OpenIDConnect.Common/Web/UserAuthenticationAction.cs

OctopusID doesn't support auth code flow yet https://github.com/OctopusDeploy/Issues/issues/7504. We'll go with the old flow until it is supported, then we should be able to remove these checks.
Feature branch instance with working OctopusID DNS prefix="nelson-s"

Add an explicit check for OctopusID when deciding auth code flow vs hybrid flow

---

source/Server.OpenIDConnect.Common/Web/UserAuthenticatedPkceAction.cs

The redirect URI was being incorrectly constructed before on cloud. This should fix that.
Feature branch instance: `nelson-s`

Calculate scheme instead of using request.Scheme

---

source/Server.OpenIDConnect.Common/Web/UserAuthenticatedPkceAction.cs

Internal discussion: https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1658237762938549
Relates to https://github.com/OctopusDeploy/Issues/issues/7681
We're removing the request blob twice if it's older than 30 seconds. In `DeleteBlobCommandHandler` we retrieve the blob before deleting which gives us a `null`. Nevermore doesn't know what to do with the `null`.
I've extended the timeout for expired blobs as I could imagine scenarios where multiple people are signing in. If they have 2FA like the customer that encountered this issue then the login process for each person can easily take more than 30 seconds. In this case other people signing in can result in another person's blob being deleted which would be bad. I've chosen 1 hour arbitrarily. This deletion only exists to ensure no old …

Fix Nevermore error appearing when the login process takes longer than 30 seconds

---

source/Server.OctopusID/OctopusIdConfigDiscoverer.cs
source/Server.OpenIDConnect.Common/Issuer/IIdentityProviderConfigDiscoverer.cs
source/Server.OpenIDConnect.Common/Issuer/IdentityProviderConfigDiscoverer.cs
source/Server.OpenIDConnect.Common/Tokens/AuthTokenHandler.cs
source/Server.OpenIDConnect.Common/Web/UserAuthenticatedPkceAction.cs
source/Server.OpenIDConnect.Common/Web/UserAuthenticationAction.cs
source/Tests/OctopusID/OctopusIdConfigDiscovererFixture.cs
source/Tests/OpenIdConnect/Tokens/OpenIDConnectAuthTokenHandlerFixture.cs
source/Tests/OpenIdConnect/Tokens/OpenIDConnectWithRolesAuthTokenHandlerFixture.cs

When we moved this provider into octopus server, we updated one of the methods on the common interface to conform to the naming convention. 
Updating it here, so that anyone loading a custom extension can bring their own dll, and not have octopus ID complain in server.

Remove async name to conform to server convention
